@echo off
echo Starting Heracle...
echo Starting Backend...
start "Heracle Backend" cmd.exe /k "cd backend && (if not exist venv python -m venv venv) && call venv\Scripts\activate.bat && pip install -r requirements.txt && uvicorn main:app --reload"
echo Starting Frontend...
start "Heracle Frontend" cmd.exe /k "npm install && npm run dev"
echo Both servers are starting up! You can close this window.
